### ISSUE TITLE
On-screen documentation for editing existing manifests

### ISSUE THREAD

**Issue by benwbrum** [bodleian/iiif-manifest-editor#10]
If a user creates a new manifest with the tool, the "add canvas" button makes it clear that the thumbnail slider is editable.  However, when editing an existing manifest--the use case I envision most frequently for documentary editors--it's not at all apparent that anything beyond canvas metadata is editable.

Perhaps a splash screen would help new users, or an info button with pop-over help?

**Comment by schwemmer** [comment]
Yes, we'll add some on-screen documentation. In the meantime, here is a wiki page with some documentation: https://github.com/bodleian/iiif-manifest-editor/wiki/User-Manual
