### ISSUE TITLE
Uploading manifests from computer

### ISSUE THREAD

**Issue by emmastanford** [bodleian/iiif-manifest-editor#12]
Editor doesn't recognize these manifests as valid (even ones that were just made and validated a minute ago with the editor).
![image](https://cloud.githubusercontent.com/assets/16155642/17694852/c7473fa0-639d-11e6-85ec-85eeff9e986d.png)

**Comment by schwemmer** [comment]
This seems to be a routing problem. I have a version of the manifest editor deployed on Heroku and upload seems to work fine: http://morning-journey-27147.herokuapp.com. 
It also works fine locally. Only on http://iiif.bodleian.ox.ac.uk/manifest-editor it doesn't seem to work. The difference between these is that the local and Heroku version are served from the root and the Bodleian version is served from a subfolder. Theoretically it should work from a subfolder too. Is the latest code (especially server.js) deployed on the Bodleian version?

**Comment by emmastanford** [comment]
Yes, we updated to the latest version yesterday morning.

**Comment by schwemmer** [comment]
Can you provide some instructions how the app is deployed so we can try to reproduce the setup/environment?

**Comment by emmastanford** [comment]
Matt did the deploying. He'll be able to provide more details later today, but he just used npm build and then copied the files to a subfolder, with nginx routing to node first, and then wsgi (for other apps on the server).

**Comment by emmastanford** [comment]
Matt's given me this list of the commands he ran:
```
git clone https://github.com/bodleian/iiif-manifest-editor.git
cd iiif-manifest-editor
nvm use v6.1.0
npm install
npm run build
sudo cp -r ~/iiif-manifest-editor /var/www
```
He then cd’d into /var/www, ran node server.js and checked it was running in a local lynx browser.
Node is being run under Supervisord on that box, so it will respawn if crashed.

The supervisord conf file reads:
```
[program:manifest-editor]
command=node server.js
directory=/var/www/iiif-manifest-editor
autostart=true  
autorestart=true  
environment=NODE_ENV=production  
stderr_logfile=/var/log/manifest-editor.err.log  
stdout_logfile=/var/log/manifest-editor.out.log
user=www-data
```

**Comment by emmastanford** [comment]
Matt just rebuilt the service and got this output, FYI.
[manifest-editor.txt](https://github.com/bodleian/iiif-manifest-editor/files/420265/manifest-editor.txt)

**Comment by schwemmer** [comment]
Thanks! I'm afraid I can't reproduce this setup locally (running the app from a subfolder) because I don't know how to install and configure Nginx locally with node. I am pretty sure the culprit is in server.js on line 18 which sets the upload path for uploading manifests. Not sure how to test this.

**Comment by mattmcgrattan** [comment]
Yes, the application always tries to call:

http://iiif.bodleian.ox.ac.uk/manifestUpload rather than http://iiif.bodleian.ox.ac.uk/iiif-manifest-editor/manifestUpload

so it 404s on the call for manifestUpload.

**Comment by mattmcgrattan** [comment]
This seems to be the case even if I explicitly add the path to the line in server.js

**Comment by schwemmer** [comment]
Thanks, Matt! I think I got it now. Can you deploy the latest code and see if the routing issue is fixed?

**Comment by emmastanford** [comment]
We tried deploying the new code on Friday and the routing problem still seemed to be the same.

**Comment by schwemmer** [comment]
Sorry for all the troubles! We were finally able to reproduce the set up locally running the app from a subfolder using reverse proxy with Apache. We think the latest commit should have finally fixed the issue. Could you please try this one more time with the latest code? Thanks!
