### ISSUE TITLE
Independent image URIs for duplicated canvases

### ISSUE THREAD

**Issue by emmastanford** [bodleian/iiif-manifest-editor#14]
When you duplicate a canvas and then change the image URI for the duplicate, it also changes the image URI for the original canvas. You can change all the other metadata independently, however, and it would be good to be able to change the image URI independently as well, as it would make it a bit easier to add new images.

**Comment by schwemmer** [comment]
Yes, you are right, the image URI on the duplicated canvas should change independently from the original canvas. This was a bug, and a tricky one too! It's all working now.
