### ISSUE TITLE
Create Help or Info Text for "Reverse Sequence Button"

### ISSUE THREAD

**Issue by schwemmer** [bodleian/iiif-manifest-editor#20]
Help text could be something like:
"Please note that this will actually reverse the order of the canvases in the sequence for this manifest. If you just want to change the viewing direction please use the viewing direction toggle button in the Sequence Metadata panel."

**Comment by emmastanford** [comment]
Yes--how about "To change the viewing direction (for example, to switch to right-to-left), please use the viewing direction toggle button in the Sequence Metadata panel."?

**Comment by schwemmer** [comment]
That sounds good. Should I add the first part of the sentence though or not? So the whole thing (with a slightly shortened version of the first part) would read like this:

"This will reverse the order of the canvases in the manifest. To change the viewing direction (for example, to switch to right-to-left), please use the viewing direction toggle button in the Sequence Metadata panel."

**Comment by emmastanford** [comment]
This looks good to me!

**Comment by schwemmer** [comment]
After discussing and reviewing this we now think it might be better to remove the "Reverse Sequence" button entirely. It might be too difficult for users to understand the difference between reversing a sequence and toggling the viewingDirection. If you reverse a sequence, the change happens "behind the scene" in the manifest and is not really visible to users except that the thumbnail strip will update the canvas order which also happens when you change the viewingDirection. After clicking the "Reverse Sequence" button multiple times you will probably lose track of what the actual sequence order is. 

@emmastanford What do you think?

**Comment by emmastanford** [comment]
I think that makes sense. It's an interesting button because it allows you to do something very easily that would otherwise be very time-consuming, but I still can't think of any reasons why someone would need to do it, and the ptoential for confusion does seem high.

**Comment by schwemmer** [comment]
Great, thanks! I'll remove it for now.
