### ISSUE TITLE
Loading invalid manifest URI breaks canvas importer?

### ISSUE THREAD

**Issue by emmastanford** [bodleian/iiif-manifest-editor#24]
I think the problem here is that the editor doesn't recover well from failing to load a manifest. Here are the steps I took to reproduce the error:

1. Loaded this manifest into the editor: https://iiif.lib.harvard.edu/manifests/drs:48309543

2. Opened the canvas importer and loaded these manifests: 
https://iiif.lib.harvard.edu/manifests/drs:5981093
http://dams.llgc.org.uk/iiif/4574752/manifest.json

3. Received a "error: invalid remote manifest URL" message when loading the last manifest. The same message appeared again when I tried to load the first manifest I had loaded (https://iiif.lib.harvard.edu/manifests/drs:48309543). When I closed the message, I couldn't close any of the manifests, open the information windows, add canvases, or return to the edit manifest view; I could only rearrange and edit the canvases that were already in my main manifest thumbnail sequence.

**Comment by schwemmer** [comment]
In fact, the DAMS manifest was valid but contained multilingual labels. We only supported multilingual values. This is fixed for the "Import Canvas" view but also needs to be fixed for the "Open Manifest" view (when editing the DAMS manifest as a target not as a source manifest). Will create a separate issue for this.
