### ISSUE TITLE
Dotted line in thumbnail strip doesn't appear when importing canvases

### ISSUE THREAD

**Issue by emmastanford** [bodleian/iiif-manifest-editor#25]
If you're dragging a canvas from an external manifest, the dotted line around the canvas in the thumbnail strip (where the imported canvas will go) doesn't appear unless you have already rearranged some of the canvases in the thumbnail strip.

**Comment by schwemmer** [comment]
When the canvases have been reordered via drag & drop, the dotted line also appears when dragging canvases from source manifests. When they haven't been reordered before, the dotted line does not appear.
