### ISSUE TITLE
error in ./app/app.jsx during installation

### ISSUE THREAD

**Issue by nvanderperren** [bodleian/iiif-manifest-editor#30]
after command `npm run build`I get an error message 
"ERROR in ./app/app.jsx
Module not found: Error: Cannot resolve module 'leaflet/dist/leaflet.css' in /Users/nastasia/iiif-manifest-editor/app
 @ ./app/app.jsx 31:0-35

I followed all steps in ReadMe

<img width="750" alt="schermafbeelding 2017-02-23 om 17 52 46" src="https://cloud.githubusercontent.com/assets/17183054/23269458/ed1fd3ce-f9f0-11e6-928d-b3a8fcbf5be0.png">

**Comment by schwemmer** [comment]
Thanks, @nvanderperren! Let me know if this fixes it.

**Comment by nvanderperren** [comment]
yes, fixed. thanks!
