### ISSUE TITLE
Regenerate public

### ISSUE THREAD

**Issue by ahankinson** [bodleian/iiif-manifest-editor#31]
The public folder should be regenerated to incorporate the latest changes. 

I can do this and create a new tag release, if appropriate.

**Comment by schwemmer** [comment]
Since the PR #32 was closed, we can close this issue too.

**Comment by ahankinson** [comment]
#32 was not the same issue. At present the `public` folder is missing a few commits from 32449ba473c6b4f2c148f42900b52a9d6d935234 onwards. It would be helpful if the `public` folder could be re-generated and re-committed.

**Comment by schwemmer** [comment]
I see. You mean the bundle.js file – the rest of the public folder is static and does not need to be regenerated. Done

**Comment by ahankinson** [comment]
Thank you!

**Comment by schwemmer** [comment]
No problem. Thanks for catching that!
