### ISSUE TITLE
Canvas dimensions don't display in editor for imported canvases

### ISSUE THREAD

**Issue by emmastanford** [bodleian/iiif-manifest-editor#36]
If you load a manifest, or import canvases from an existing manifest, the image dimensions appear to be blank.

To reproduce:
Click "Load manifest" and enter http://digi.vatlib.it/iiif/MSS_Vat.lat.3773/manifest.json.
Check canvas dimensions in the Canvas Metadata section.

Dimensions do appear if you add an image onto a canvas via changing the image URI. Should these be non-editable?

**Comment by schwemmer** [comment]
No, they should be editable. The issue was that we changed them from strings to integers (as required by the specification) at some point but the component can only render strings. Now they get rendered as strings and stored as integers which should fix this issue.
