### ISSUE TITLE
Editing structural maps

### ISSUE THREAD

**Issue by nemobis** [bodleian/iiif-manifest-editor#42]
I've read the README and user manual but I find it's missing one detail: whether this product can be used to produce and edit IIIF manifests to a level of detail similar to that of the [structMap in METS](https://www.loc.gov/standards/mets/METSOverview.html#structmap).

For an example of what I mean, please see the TOC in a volume like https://gutenberg.beic.it/webclient/DeliveryManager?pid=2386355

**Comment by schwemmer** [comment]
In IIIF this would be done with Ranges: http://iiif.io/api/presentation/2.0/#ranges
The Manifest Editor currently does not support creating or editing IIIF Ranges. If you have existing METS metadata you might want to look into the Digital Manuscripts Toolkit's Metadata Transformation Tools: http://dmt.bodleian.ox.ac.uk/metadata-transformation-tools/
