### ISSUE TITLE
possible to override save callback?

### ISSUE THREAD

**Issue by nicolasfranck** [bodleian/iiif-manifest-editor#47]
The save button generates a manifest for you to download.
Another option would be to supply a callback so one can upload
this manifest wherever you want. This way this UI can be used
as an editor for an admin interface.

Or is this just intended as an application that edits and exports manifests?

**Comment by schwemmer** [comment]
@nicolasfranck What you suggest is exactly what we have been working on over the last couple of months. I just merged the changes to master. Please check out the [latest release](https://github.com/bodleian/iiif-manifest-editor/releases/tag/v0.7.0).

With this release you can go to the settings and configure a server endpoint to store your manifests remotely. You can either use myJson (pre-configured) or [iiif-manifest-store](https://github.com/textandbytes/iiif-manifest-store) which we have built for this purpose or create your own. If you want to build your own, it has to support the same kind of API as [iiif-manifest-store](https://github.com/textandbytes/iiif-manifest-store):

## API ##

| Route                      | HTTP Verb     | Description                                         |
| -------------------------- | ------------- | --------------------------------------------------- |
| /api/manifests             | GET           | Get all manifests                                   |
| /api/manifests             | POST          | Create a manifest - returns manifest uri            |
| /api/manifests/:manifestId | GET           | Get manifest by id                                  |
| /api/manifests/:manifestId | PUT           | Update manifest with id                             |
| /api/manifests/:manifestId | DELETE        | Delete manifest with id (currently not implemented) |

Let me know if this answers your question.

**Comment by schwemmer** [comment]
Thanks! Yes, your understanding of how it works is correct. This way it's more flexible since you can specify where you want to host the manifest and also it's not meant to be a manifest hosting application but a manifest editing application. You could fork it and add the ability to store manifests on the same server but the stakeholders of this project specifically don't want to host the manifests on their own server. Also, a lot of people use it locally on their own computer.
