### ISSUE TITLE
Save manifest to myjson.com does not work anymore

### ISSUE THREAD

**Issue by mnscholz** [bodleian/iiif-manifest-editor#53]
The site myjson.com is set as default when creating a new manifest at https://digital.bodleian.ox.ac.uk/manifest-editor .

However, it seems to be down for some time.

Does anyone know a replacement store?

**Comment by schwemmer** [comment]
Too bad that myjson.com doesn't work anymore. It seems to be permanently down.

You could use this alternative:
https://github.com/textandbytes/iiif-manifest-store

But you would have to host it yourself.

**Comment by mnscholz** [comment]
ok. Thanks for the hint!

**Comment by schwemmer** [comment]
You're welcome. I actually want to leave this issue open because it doesn't look like myjson.com is coming back, in which case it should be removed as the default store and some of the dialogs need to be updated.

**Comment by regisrob** [comment]
Hi Rafael 😉  FWIW I've recently managed to configure a new JSON endpoint (directly through the Manifest Editor UI, which is great!) and store my custom Manifest on this 3rd-party service: https://jsonstorage.net
The endpoint URL is: https://jsonstorage.net/api/items
The question is: how long will it stay alive? 😬

**Comment by schwemmer** [comment]
Hi Régis! That's great! Maybe I can configure this as the default (when I get to it). Thanks for the tip!

**Comment by schwemmer** [comment]
@mnscholz Thanks for bringing this to my attention. I replaced myJson.com with JsonStorage.net as suggested by Régis, so the remote storage feature is now available again and you don't need to host anything yourself. You can see it in action here:
http://iiif-manifest-editor.textandbytes.com/ (don't forget to delete your browser cache first)

@regisrob Thanks again for the great suggestion, Régis, it works like a charm!

**Comment by schwemmer** [comment]
PS: this also fixes manifest validation which was going through myJson.com and now goes through JsonStorage.net (can't POST directly to the IIIF Validator)

**Comment by regisrob** [comment]
Thanks Rafael, that was a quick fix! Cheers from Paris

**Comment by mnscholz** [comment]
Thanks for the fix!

Your changes, however, only apply to the editor found on http://iiif-manifest-editor.textandbytes.com/ , but not to the version I mentioned first at https://digital.bodleian.ox.ac.uk/manifest-editor . Will the latter also be updated?

**Comment by schwemmer** [comment]
Yes

**Comment by ahankinson** [comment]
I've just updated the Bodleian hosted manifest editor to the latest version. You may need to clear your browser caches if it doesn't work as expected.
