### ISSUE TITLE
Error loading remote manifest

### ISSUE THREAD

**Issue by Tamarae** [bodleian/iiif-manifest-editor#59]
Hi,
I am writing on behalf of the Silk Museum. We have been using https://digital.bodleian.ox.ac.uk for creating manifests of the photo collection. Unfortunately we have been receiving an error recently, is this a temporary thing or should we be searching for other ways to create/edit manifestos?

**Comment by Tamarae** [comment]
<img width="1479" alt="Screenshot 2022-01-28 at 15 23 51" src="https://user-images.githubusercontent.com/2108388/151539313-1c87b0ce-611e-445d-92e3-10ede2f698b8.png">

**Comment by ahankinson** [comment]
Loading that manifest results in a 404 Not Found for me: https://www.jsonstorage.net/api/items/aa4bfa74-7d56-468b-9aa9-727f4b87dee9

**Comment by Tamarae** [comment]
We have been storing manifests on jsonstorage as there was such an option, we were using this URL to share and open manifest in Mirador, does this mean that the manifest is lost?

**Comment by ahankinson** [comment]
I don't know -- I am not sure if the URL is just mistyped, or if it actually was deleted. 

I notice the 'free tier' has a limit of 50 items, so this quota has been exceeded? In any case, you should probably save your manifests locally instead of storing them in jsonstorage, as I believe that is only offered for demonstration purposes.

**Comment by schwemmer** [comment]
If this is the only place where you stored the manifest, I am afraid it might be lost. I found this tweet, which says that the jsonstorage API is being deprecated: https://twitter.com/jsonstorage/status/1451923623586025475

As Andrew said, this option was offered for demonstration purposes. "Please note that your content on JsonStorage.net is publicly visible and the service might not be suitable for long-term storage of IIIF manifests."

Maybe you can contact them and ask about your manifest. Their Github is here: https://github.com/jsonstorage/docs

**Comment by schwemmer** [comment]
I have updated the JsonStorage endpoint URI and made the warning more clear, that this should not be used as the main storage solution (see 149a3bd)
