### ISSUE TITLE
Broken URL in Github About section

### ISSUE THREAD

**Issue by regisrob** [bodleian/iiif-manifest-editor#67]
See http://dmt.bodleian.ox.ac.uk/manifest-editor/ on this repo homepage

**Comment by schwemmer** [comment]
Looks like I can't update the "About" section. @mel-mason can you update it?

**Comment by mel-mason** [comment]
I've updated it to http://dmt.bodleian.ox.ac.uk/ , which still exists

**Comment by schwemmer** [comment]
Thank you @mel-mason and @regisrob!
